build.product_name = Hacker Simulator: Zero Day
build.product_identifier = com.absurdgames.hacksim
build.product_version = 1.3
build.product_version_semantic = 1.3.0
build.shared_library_excludes = plist TrueAudioNext GPUUtilities systemd_notify sqlite git2
build.android_manifest = AndroidManifest.xml